### ISSUE TITLE
way to pass metadata

### ISSUE THREAD

**Issue by jakubzloczewski** [Sliverb/multer-azure-blob-storage#1]
Hi, thanks for sharing your work. It's great! 

I'm curious if there is any possibility to write metadata while uploading file or do you have any plans to make it possible? I imagine it would work similar to name resolver.

Best,
Jakub

**Comment by Sliverb** [comment]
I never thought about that but that should be relatively straight fwd. What kind of metadata are you thinking?

**Comment by jakubzloczewski** [comment]
I was thinking about metadata just like strings, Dates etc. In my case I need to store some references to objects from database.

**Comment by Sliverb** [comment]
Sounds good. I will get experimenting on this.

**Comment by Sliverb** [comment]
Sorry on being delayed on this. got pulled in on a hot project.

**Comment by Sliverb** [comment]
@jakubzloczewski This should be in. Its implemented similar to the name resolver. This allows you to add custom metadata per file. If all the files will have the same metadata, then you  can just include the object list too (simpler).

Hope this helps and sorry for the delay in implementing this
