### ISSUE TITLE
sas token for containerAccessLevel = 'blob' doesn't make sense

### ISSUE THREAD

**Issue by jakubzloczewski** [Sliverb/multer-azure-blob-storage#2]
Please correct me if I'm wrong. 

My understanding is that containers with type of 'Blob' are accessible anonymously - so generating sas tokens for this type of container is redundant. 

I've tried with files from my Blob container and when I have generated url with expired signature then file is not accessible but when I remove all parameters from url then anyone can open file.

**Comment by Sliverb** [comment]
You are right. From my understanding, i thought we were able to set different permission levels for the container/blobs. I just tried removing the params as you suggested and surprised i could also open the file.

I'll have to go figure out if blob access level can be secured. 

Thanks for this new knowlege

**Comment by Sliverb** [comment]
Closing for now as it doesn't affect functionality. But I will improve on this to skip the tokens for blob types
