### ISSUE TITLE
 Cannot find namespace 'Express'

### ISSUE THREAD

**Issue by SharpFu** [Sliverb/multer-azure-blob-storage#3]
the error is "Cannot find namespace 'Express' " ,bug I do not fond Express in package.json。why

**Comment by SharpFu** [comment]
i found the file in lib/MulterAzureStorage.d.ts need import Express from express,please check it.
and I hava an other question about use azure blob.that is flow:
when i use "PUT" mthods and SAS services  to upload a file, such as : 
 this.http.put('https://xxx.blob.core.chinacloudapi.cn/msl-develop-files/%E9%82%AE%E7%AE%B1.png?sig=xxxxxxxx&se=2018-04-19T05%3A42%3A45Z&sv=2015-07-08&sp=rc&sr=b', fileInfo).subscribe(data=>{
         });
 and i get the error is "An HTTP header that's mandatory for this request is not specified" ,I want to know that  there is need to add Authorization to the headers when use SAS services?

**Comment by Sliverb** [comment]
Thanks for researching this for me. I will try and get the fix out this week

**Comment by Sliverb** [comment]
Hi SharpFu, I am unable to reproduce this error. Express is only referenced in the lib, so I didn't import the whole lib. The ref is imported by @types/multer

Some questions to help us get this fixed
- Are you using Express or another node framework like Hapi?
- Try installing @types/multer as a dependency to see if this gets fixed (maybe my dependency imports failed)
